name: Android APK PreRelease

on:
  push:
    tags:
      - "v*-alpha"
      - "v*-beta"
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Write gradle.properties
        run: |
          cat > gradle.properties <<EOF
          org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
          android.useAndroidX=true
          kotlin.code.style=official
          android.nonTransitiveRClass=true

          WEB_CLIENT_ID=${{ secrets.WEB_CLIENT_ID }}
          ZEGOCLOUD_APP_ID=${{ secrets.ZEGOCLOUD_APP_ID }}
          ZEGOCLOUD_APP_SIGN=${{ secrets.ZEGOCLOUD_APP_SIGN }}
          EOF

      - run: cat gradle.properties

      - name: Decode google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      - name: Build APK
        run: ./gradlew assembleRelease
        
      - name: List APK outputs
        run: |
          find app/build/outputs -type f

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: |
            app/build/outputs/apk/release/app-release.apk
